export default () => ({
    tasksArray: [],
    statusArray: ['OPEN', 'DONE'],
    isLoading: false,
    filterOptions:{
        taskText:null,
        taskStatus: [],
        taskTargetDateFrom: null,
        taskTargetDateTo: null,
    },
    emptyTaskObj: {
        text: null,
        status: null,
        target_date: null,
    },
    form: {
        name: 'Task Info',
        icon: 'mdi-eye',
        color: 'info',
        action: false,
        disabled: true,
        submit:true,
    },
    formObj: {
        edit: {
            name: 'Edit Task',
            icon: 'mdi-pencil',
            color: 'primary',
            action: 'tasks/updateTaskById',
            disabled: false,
            submit:true,
        },
        create: {
            name: 'Create Task',
            icon: 'mdi-plus',
            color: 'success',
            action: 'tasks/createNewTask',
            disabled: false,
            submit:true,
        },
        delete: {
            name: 'Delete Task',
            icon: 'mdi-delete-forever',
            color: 'error',
            action: 'tasks/deleteTaskById',
            disabled: true,
            submit:true,
        },
        display: {
            name: 'Task Info',
            icon: 'mdi-eye',
            color: 'secondary',
            action: false,
            disabled: true,
            submit:false,
        },
    },
    selectedTask: null,
    showForm: false,
    formTitle: '',
    formType: 'edit',
    showDialog: false,
    dialogTitle: '',
    dialogText: '',
    dialogType: 'info'
});
